LegalSystem/Controllers/TrayController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using LegalData.Model;
using LegalData.Model.EF;
using LegalData.Model.Request;
using LegalSystem.App_Start;
using LegalSystem.Common;
using LegalSystem.Model;
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static LegalSystem.Common.GlobalSession;

namespace LegalSystem.Controllers
{

    public class TrayController : Controller
    {
        private LegalData.Repository.LegalEntities business = new LegalData.Repository.LegalEntities();
        private LegalData.LegalSystemEntities db = new LegalData.LegalSystemEntities();

        [SessionTimeout]
        public ActionResult Tray1()
        {
            TrayViewModel model = new TrayViewModel();

            var DocumentTypes = db.msDocumentTypes
                .Where(o => o.ReqTypeID.Equals(1) || o.ReqTypeID.Equals(2))
                .Select(p => new { Value = p.DocTypeID, Text = p.DocTypeName });

            ViewBag.DocumentTypeID = new SelectList(DocumentTypes, "Value", "Text");
            ViewBag.DocumentStatusID = new SelectList(db.msDocumentStatus.Select(p => new { Value = p.DocStatusID, Text = p.DocStatusName ?? p.DocStatusDesc }), "Value", "Text");

            return View(model);
        }

        [SessionTimeout]
        public ActionResult Tray2()
        {
            TrayViewModel model = new TrayViewModel();

            var DocumentTypes = db.msDocumentTypes
                .Where(o => o.ReqTypeID.Equals(3) || o.ReqTypeID.Equals(4) || o.ReqTypeID.Equals(5))
                .Select(p => new { Value = p.DocTypeID, Text = p.DocTypeName });

            ViewBag.DocumentTypeID = new SelectList(DocumentTypes, "Value", "Text");
            ViewBag.DocumentStatusID = new SelectList(db.msDocumentStatus.Select(p => new { Value = p.DocStatusID, Text = p.DocStatusName ?? p.DocStatusDesc }), "Value", "Text");

            return View(model);
        }

        [SessionTimeout]
        public ActionResult Tray3()
        {
            TrayViewModel model = new TrayViewModel();
            var DocumentTypes = db.msDocumentTypes
                  .Where(o => o.ReqTypeID.Equals(6) || o.ReqTypeID.Equals(7) || o.ReqTypeID.Equals(8) || o.ReqTypeID.Equals(9) || o.ReqTypeID.Equals(10) || o.ReqTypeID.Equals(18))
                  .Select(p => new { Value = p.DocTypeID, Text = p.DocTypeName });

            ViewBag.DocumentTypeID = new SelectList(DocumentTypes, "Value", "Text");
            ViewBag.DocumentStatusID = new SelectList(db.msDocumentStatus.Select(p => new { Value = p.DocStatusID, Text = p.DocStatusName ?? p.DocStatusDesc }), "Value", "Text");

            return View(model);
        }

        [SessionTimeout]
        public ActionResult Tray4()
        {
            TrayViewModel model = new TrayViewModel();
            var DocumentTypes = db.msDocumentTypes
                  .Where(o => o.ReqTypeID.Equals(1) || o.ReqTypeID.Equals(8) || o.ReqTypeID.Equals(9) || o.ReqTypeID.Equals(10))
                  .Select(p => new { Value = p.DocTypeID, Text = p.DocTypeName });

            ViewBag.DocumentTypeID = new SelectList(DocumentTypes, "Value", "Text");
            ViewBag.DocumentStatusID = new SelectList(db.msDocumentStatus.Select(p => new { Value = p.DocStatusID, Text = p.DocStatusName ?? p.DocStatusDesc }), "Value", "Text");

            return View(model);
        }

        [SessionTimeout]
        public ActionResult Tray5()
        {
            TrayViewModel model = new TrayViewModel();
            var DocumentTypes = db.msDocumentTypes
         .Where(o => o.ReqTypeID.Equals(8) || o.ReqTypeID.Equals(11) || o.ReqTypeID.Equals(12))
         .Select(p => new { Value = p.DocTypeID, Text = p.DocTypeName });

            ViewBag.DocumentTypeID = new SelectList(DocumentTypes, "Value", "Text");
            ViewBag.DocumentStatusID = new SelectList(db.msDocumentStatus.Select(p => new { Value = p.DocStatusID, Text = p.DocStatusName ?? p.DocStatusDesc }), "Value", "Text");

            return View(model);
        }

        [HttpPost]
        [SessionTimeout]
        public JsonResult Search(DataTableModel model, int TrayID)
        {
            var columns = model.columns.Where(o => !string.IsNullOrEmpty(o.search.value)).ToList();
            var filters = new List<FieldModel>();
            filters.Add(new FieldModel { Name = "TrayID", Value = TrayID, DataType = System.Data.SqlDbType.Int });

            //System Parameter
            filters.Add(new FieldModel { Name = "PermissionID", Value = ((PermissionID)GlobalSession.GetPermission).ToString() });
            filters.Add(new FieldModel { Name = "UserID", Value = GlobalSession.UserLogin.Emp_Code });

            columns.ForEach(column =>
            {
                filters.Add(new FieldModel { Name = column.data, Value = column.search.value });
            });

            var orders = new List<OrderByModel>();
            if (model.order != null)
            {
                model.order.ForEach(o =>
                {
                    var col = model.columns[o.column];
                    orders.Add(new OrderByModel { Name = col.data, SortDirection = (o.dir.Equals("desc") ? SortDirection.Descending : SortDirection.Ascending) });
                });
            }

            var result = business.Tray.Search(new BaseParameterModel()
            {
                Paging = new PagingModel { Start = model.start, Limit = model.length },
                Orders = orders,
                Parameters = filters
            });

 



            return Json(new
            {
                draw = model.draw,
                recordsTotal = result.Total,
                recordsFiltered = result.Total,
                data = result.Data.Trays
            });
        }

        [HttpPost]
        public async Task<JsonResult> TrayActionAsync(int trayID)
        {
            ResultWithModel rwm = new ResultWithModel();
            RequestSignatureModel rsm = new RequestSignatureModel();

            try
            {
                var signature = Request.Headers.GetValues("signature").FirstOrDefault();
                var SignatureResult = business.System.RequestSignature(signature);

                if (SignatureResult.Success)
                {
                    rsm = SignatureResult.Data;
                }

                else
                {
                    rwm.Success   = SignatureResult.Success;
                    rwm.Message   = SignatureResult.Message;
                    rwm.RefCode   = SignatureResult.RefCode;
                    rwm.Serverity = SignatureResult.Serverity;

                    return Json(rwm, JsonRequestBehavior.AllowGet);
                }

                var _request =   await db.trRequests.FindAsync(new Guid(rsm.RequestID));

                if (_request == null) {


                    rwm.RefCode = 404;
                    rwm.Success = false;
                    rwm.Message = "Data not found";

                    return Json(rwm );
                }

                int RequestTypeID = 0;

                if (int.TryParse(_request.RequestType, out RequestTypeID))
                {
                    var result = business.Tray.GetTrayActionDocument(RequestTypeID, trayID);

                    rwm.Success = result.Success;
                    rwm.Message = result.Message;
                    rwm.Serverity = result.Serverity;
                    rwm.Total = result.Total;
                    rwm.RefCode = result.RefCode;

                    if (result.Success)
                    {
                        rwm.Data = result.Data;
                    }
                }

                else {
                    rwm.RefCode = 500;
                    rwm.Success = false;
                    rwm.Message = "String request type cannot be converted into Integer";
                }

            }

            catch (Exception ex)
            {

                rwm.RefCode = 500;
                rwm.Success = false;
                rwm.Message = ex.Message;
            }

            return Json(rwm, JsonRequestBehavior.AllowGet);
        }
 
        [HttpPost]
        public JsonResult ButtonPermission()
        {
            ResultWithModel rwm = new ResultWithModel();
            RequestSignatureModel rsm = new RequestSignatureModel(); 

            try
            {
                var signature       = Request.Headers.GetValues("signature").FirstOrDefault();
                var SignatureResult = business.System.RequestSignature(signature);

                if (SignatureResult.Success)
                {
                    rsm = SignatureResult.Data;
                }

                else
                {
                    rwm.Success     = SignatureResult.Success    ;
                    rwm.Message     = SignatureResult.Message    ;
                    rwm.RefCode     = SignatureResult.RefCode    ;
                    rwm.Serverity   = SignatureResult.Serverity  ;

                    return Json(rwm, JsonRequestBehavior.AllowGet);
                }

                //get permisstion
               var ButtonPermissionresult= business.Tray.GetButtonPermission(new BaseParameterModel()  {
                    Parameters = new List<FieldModel>() {
                          new FieldModel { Name = "PermissionID", Value =  rsm.PermissionID }
                        , new FieldModel { Name = "UserID", Value =  rsm.UserID }
                        , new FieldModel { Name = "RequestID", Value = rsm.RequestID }
                    }
                });

                rwm.Success     = ButtonPermissionresult.Success    ;
                rwm.Message     = ButtonPermissionresult.Message    ;
                rwm.RefCode     = ButtonPermissionresult.RefCode    ;

LegalSystem/Views/Tray/Tray1.cshtml
@model  LegalSystem.Model.TrayViewModel

@{
    ViewBag.Title = "รับเรื่องดำเนินคดี";
}


@section Styles {
    <style>

        select.form-control:not([size]):not([multiple]) {
            height: 36px;
            color: #aaa;
        }

        /*.table thead tr th {
            font-size: 14px !important;
        }*/

        /*.dataTables_filter {
                display: none;
            }*/

        /*div.dataTables_wrapper {
                width: 100%;
                margin: 0 auto;
            }*/

        .label-select {
            position: absolute;
            top: -4px;
            margin-left: -5px;
        }

         label {
            line-height: 0;
        }

        .dataTables_filter, 
        .dataTables_length {
            display: none;
        }
    </style>
}

<div class="row">


    <div class="col-lg-12">
        @using (Html.BeginForm("Search", "Tray", FormMethod.Post, new { @class = "form-horizontal", id = "search-form" }))
        {
            <div class="card ">

                <div class="card-header card-header-tabs card-header-info">
                    <h4 id="trayname" class="card-title">@ViewBag.Title</h4>
                </div>
                <div class="card-body">

                    <div class="form-row">
                        <div class="col form-group">
                            @Html.LabelFor(m => m.RequestNo, htmlAttributes: new { @class = "label-floating" })
                            @Html.EditorFor(m => m.RequestNo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col form-group">
                            @Html.LabelFor(m => m.CIFNo, htmlAttributes: new { @class = "label-floating" })
                            @Html.EditorFor(m => m.CIFNo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col form-group">
                            @Html.LabelFor(m => m.AssignOAName, htmlAttributes: new { @class = "label-floating" })
                            @Html.EditorFor(m => m.AssignOAName, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>


                    <div class="form-row">
                        <div class="col form-group">
                            @Html.LabelFor(m => m.LegalNo, htmlAttributes: new { @class = "label-floating" })
                            @Html.EditorFor(m => m.LegalNo, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="col form-group">
                            @Html.LabelFor(m => m.DocumentTypeID, htmlAttributes: new { @class = "label-floating label-select" })
                            @Html.DropDownListFor(m => m.DocumentTypeID, (SelectList)ViewBag.DocumentTypeID, "-- Please select --", new { @class = "form-control" })
                        </div>
                        <div class="col form-group">
                            @Html.LabelFor(m => m.DocumentStatusID, htmlAttributes: new { @class = "label-floating label-select" })
                  
                            @Html.DropDownListFor(m => m.DocumentStatusID, (SelectList)ViewBag.DocumentStatusID, "-- Please select --", new { @class = "form-control" })
                       
                        </div>
                    </div>
 
                   
                </div>

                <div class="card-footer">

                    <div class="form-group mb">
                        <div class="col-xs-12">
                            <button class="btn btn-primary btn-main btn-search" type="submit">Search</button>
                            <button class="mb-sm btn btn-outline-secondary" type="reset">Clear</button>
                        </div>
                    </div>
                </div>

            </div>
        }

    </div>

</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card" style="margin-top:50px;">
            <div class="card-header card-header-tabs card-header-info">
                <h4 class="card-title">SEARCH RESULT</h4>
            </div>
            <div class="card-body">

                <div class="material-datatables table-responsive">
                    <table id="table-tray" class="table table-striped table-no-bordered table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Req No</th>
                                <th>Request Type ID</th>
                                <th>Request Type</th>
                                <th>CIF No</th>
                                <th>Name</th>
                                <th>Legal No</th>
                                <th>Legal Status</th>
                                <th>SLA OA Send Date</th>
                                <th>Assign OA ID</th>
                                <th>Assign OA</th>
                                <th>Tray Action ID</th>
                                <th>Document Type</th>
                                <th>Document Status ID</th>
                                <th>Document Status</th>
                                <th>วันที่ออกหนังสือ</th>
                                <th>Loan Type</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody> </tbody>
                    </table>
                </div>
            </div>

            <div class="card-footer">

            </div>
        </div>
    </div>
</div>


@section Scripts {

    <script>

            $(document).ready(function () {

                var Tray = {};
                Tray.Form = {};
                Tray.Form.Table = $('#table-tray').DataTable({
                    order: [[1, "desc"]],
                    // scrollY: '70vh',
                    scrollX: true,
                    searching: true,
                    processing: true,
                    serverSide: true,
                    ajax: {
                        "url": "@Url.Action("Search", (string)this.ViewContext.RouteData.Values["controller"])",
                        "type": "POST",
                        "data": {
                            "TrayID": 1
                        }
                    },
                    columnDefs: [

                        { targets: 0, data: "RowNo", orderable: false, width: 30 },
                        { targets: 1, data: "RequestNo" },
                        { targets: 2, data: "RequestTypeID", "visible": false },
                        { targets: 3, data: "RequestTypeName", width: 200 },
                        { targets: 4, data: "CIFNo" },
                        { targets: 5, data: "CIFName" },
                        { targets: 6, data: "LegalNo" },
                        { targets: 7, data: "LegalStatusName", width: 100 },
                        //{ targets: 8, data: "SLASendDate", width: 100 },

                        {
                            targets: 8, data: "SLASendDate", width: 100, render: function (data, type, row, meta) {
                                if (data) {

                                    return moment(data).local().format('DD/MM/YYYY');
                                }
                                return data
                            }
                        },

                        { targets: 9, data: "AssignOAID", "visible": false },
                        { targets: 10, data: "AssignOAName" },
                        { targets: 11, data: "TrayActionID", "visible": false },
                        { targets: 12, data: "TrayActionName" },
                        { targets: 13, data: "DocumentStatusID", "visible": false },
                        { targets: 14, data: "DocumentStatusName" },
                     

                        {
                            targets: 15, data: "PrintDate", width: 100, render: function (data, type, row, meta) {
                                if (data) {

                                    return moment(data).local().format('DD/MM/YYYY HH:mm');
                                }
                                return data
                            }
                        },

                        { targets: 16, data: "LoanType" },
                        {
                            targets: 17,
                            data: "RequestID",
                            width: 60,
                            render: function (data, type, row, meta) {
                                var html = '';
                                html += '<button type="button" class="mb-sm btn btn-outline-info" form-mode="edit"  onclick="location.href=\'/LegalSystem_DEV/Pages/LegalInfo.aspx?rid=' + row.RequestID + '\'" ><i class="icon-pencil "></i> View</button>';

                                return html;

                                return "";
                            }
                        },

                        { targets: 18, data: "RequestID", "visible": false },
                        { targets: 19, data: "LegalID", "visible": false }
                    ]

                    , fixedColumns: {
                        leftColumns: 3,
                        rightColumns: 19
                    }
                });

                Tray.Form.Search = function () {
                    console.log("search processing...");

                    $('#search-form :input').each(function () {
                        var input = $(this);
                        var key = input[0].name;

                        switch (key) {
                            case "RequestNo": Tray.Form.Table.columns(1).search($(this).val()); break;
                            case "CIFNo": Tray.Form.Table.columns(4).search($(this).val()); break;
                            case "AssignOAName": Tray.Form.Table.columns(10).search($(this).val()); break;
                            case "LegalNo": Tray.Form.Table.columns(6).search($(this).val()); break;
                            case "TrayActionID": Tray.Form.Table.columns(11).search($(this).val()); break;
                            case "DocumentStatusID": Tray.Form.Table.columns(13).search($(this).val()); break;

                        }
                    });

                    Tray.Form.Table.draw();
                }

                $("#search-form").on('submit', function (e) {
                    e.preventDefault();

                    setTimeout(function () {
                        Tray.Form.Search();
                    }, 100);

                });

                $("#search-form").on('reset', function (e) {

                    setTimeout(function () {

                        $(".is-filled").removeClass("is-filled");

                        Tray.Form.Search();

                    }, 100);

                });

            });

    </script>

}